/**
 * componentRegistry.ts
 * Charlie Platform -- Registro de componentes de vistas.
 * Mapea slug (modulos_disponibles.slug) a React.lazy().
 * Es el UNICO lugar donde se registra una vista nueva.
 * Zero hardcoding de modulos activos -- eso viene de Supabase.
 */
import React from 'react';

export const COMPONENT_REGISTRY: Record<string, React.LazyExoticComponent<React.ComponentType<any>>> = {
  'APIKeysView': React.lazy(() => import('../components/admin/views/APIKeysView').then(m => ({ default: m.APIKeysView }))  ),
  'AbastecimientoView': React.lazy(() => import('../components/admin/views/AbastecimientoView').then(m => ({ default: m.AbastecimientoView }))  ),
  'AdminDashboardView': React.lazy(() => import('../components/admin/views/AdminDashboardView').then(m => ({ default: m.AdminDashboardView }))  ),
  'AuditoriaHubView': React.lazy(() => import('../components/admin/views/AuditoriaHubView').then(m => ({ default: m.AuditoriaHubView }))  ),
  'AuthRegistroView': React.lazy(() => import('../components/admin/views/AuthRegistroView').then(m => ({ default: m.AuthRegistroView }))  ),
  'BibliotecaWorkspace': React.lazy(() => import('../components/admin/views/BibliotecaWorkspace').then(m => ({ default: m.BibliotecaWorkspace }))  ),
  'CargaMasivaView': React.lazy(() => import('../components/admin/views/CargaMasivaView').then(m => ({ default: m.CargaMasivaView }))  ),
  'ChecklistView': React.lazy(() => import('../components/admin/views/ChecklistView').then(m => ({ default: m.ChecklistView }))  ),
  'ClientesView': React.lazy(() => import('../components/admin/views/ClientesView').then(m => ({ default: m.ClientesView }))  ),
  'ConfigVistasPorRolView': React.lazy(() => import('../components/admin/views/ConfigVistasPorRolView').then(m => ({ default: m.ConfigVistasPorRolView }))  ),
  'ConstruccionView': React.lazy(() => import('../components/admin/views/ConstruccionView').then(m => ({ default: m.ConstruccionView }))  ),
  'ConstructorModulos': React.lazy(() => import('../components/admin/views/ConstructorModulos').then(m => ({ default: m.ConstructorModulos }))  ),
  'ConstructorView': React.lazy(() => import('../components/admin/views/ConstructorView').then(m => ({ default: m.ConstructorView }))  ),
  'DashboardView': React.lazy(() => import('../components/admin/views/DashboardView').then(m => ({ default: m.DashboardView }))  ),
  'DepartamentosView': React.lazy(() => import('../components/admin/views/DepartamentosView').then(m => ({ default: m.DepartamentosView }))  ),
  'DepositosView': React.lazy(() => import('../components/admin/views/DepositosView').then(m => ({ default: m.DepositosView }))  ),
  'DisenoView': React.lazy(() => import('../components/admin/views/DisenoView').then(m => ({ default: m.DisenoView }))  ),
  'DocumentacionView': React.lazy(() => import('../components/admin/views/DocumentacionView').then(m => ({ default: m.DocumentacionView }))  ),
  'ERPCRMView': React.lazy(() => import('../components/admin/views/ERPCRMView').then(m => ({ default: m.ERPCRMView }))  ),
  'ERPComprasView': React.lazy(() => import('../components/admin/views/ERPComprasView').then(m => ({ default: m.ERPComprasView }))  ),
  'ERPContabilidadView': React.lazy(() => import('../components/admin/views/ERPContabilidadView').then(m => ({ default: m.ERPContabilidadView }))  ),
  'ERPFacturacionView': React.lazy(() => import('../components/admin/views/ERPFacturacionView').then(m => ({ default: m.ERPFacturacionView }))  ),
  'ERPInventarioView': React.lazy(() => import('../components/admin/views/ERPInventarioView').then(m => ({ default: m.ERPInventarioView }))  ),
  'ERPRRHHView': React.lazy(() => import('../components/admin/views/ERPRRHHView').then(m => ({ default: m.ERPRRHHView }))  ),
  'EcommerceView': React.lazy(() => import('../components/admin/views/EcommerceView').then(m => ({ default: m.EcommerceView }))  ),
  'EditorImagenesWorkspace': React.lazy(() => import('../components/admin/views/EditorImagenesWorkspace').then(m => ({ default: m.EditorImagenesWorkspace }))  ),
  'EntregasView': React.lazy(() => import('../components/admin/views/EntregasView').then(m => ({ default: m.EntregasView }))  ),
  'EnviosView': React.lazy(() => import('../components/admin/views/EnviosView').then(m => ({ default: m.EnviosView }))  ),
  'EtiquetaEmotivaView': React.lazy(() => import('../components/admin/views/EtiquetaEmotivaView').then(m => ({ default: m.EtiquetaEmotivaView }))  ),
  'FidelizacionView': React.lazy(() => import('../components/admin/views/FidelizacionView').then(m => ({ default: m.FidelizacionView }))  ),
  'FulfillmentView': React.lazy(() => import('../components/admin/views/FulfillmentView').then(m => ({ default: m.FulfillmentView }))  ),
  'GenDocumentosWorkspace': React.lazy(() => import('../components/admin/views/GenDocumentosWorkspace').then(m => ({ default: m.GenDocumentosWorkspace }))  ),
  'GenPresupuestosWorkspace': React.lazy(() => import('../components/admin/views/GenPresupuestosWorkspace').then(m => ({ default: m.GenPresupuestosWorkspace }))  ),
  'GestionView': React.lazy(() => import('../components/admin/views/GestionView').then(m => ({ default: m.GestionView }))  ),
  'GoogleAdsView': React.lazy(() => import('../components/admin/views/GoogleAdsView').then(m => ({ default: m.GoogleAdsView }))  ),
  'GoogleMapsTestView': React.lazy(() => import('../components/admin/views/GoogleMapsTestView').then(m => ({ default: m.GoogleMapsTestView }))  ),
  'HealthMonitorView': React.lazy(() => import('../components/admin/views/HealthMonitorView').then(m => ({ default: m.HealthMonitorView }))  ),
  'HerramientasView': React.lazy(() => import('../components/admin/views/HerramientasView').then(m => ({ default: m.HerramientasView }))  ),
  'IdeasBoardView': React.lazy(() => import('../components/admin/views/IdeasBoardView').then(m => ({ default: m.IdeasBoardView }))  ),
  'IdeasView': React.lazy(() => import('../components/admin/views/IdeasView').then(m => ({ default: m.IdeasView }))  ),
  'ImpresionWorkspace': React.lazy(() => import('../components/admin/views/ImpresionWorkspace').then(m => ({ default: m.ImpresionWorkspace }))  ),
  'IntegracionesComunicacionView': React.lazy(() => import('../components/admin/views/IntegracionesComunicacionView').then(m => ({ default: m.IntegracionesComunicacionView }))  ),
  'IntegracionesIdentidadView': React.lazy(() => import('../components/admin/views/IntegracionesIdentidadView').then(m => ({ default: m.IntegracionesIdentidadView }))  ),
  'IntegracionesLogisticaView': React.lazy(() => import('../components/admin/views/IntegracionesLogisticaView').then(m => ({ default: m.IntegracionesLogisticaView }))  ),
  'IntegracionesMarketplaceView': React.lazy(() => import('../components/admin/views/IntegracionesMarketplaceView').then(m => ({ default: m.IntegracionesMarketplaceView }))  ),
  'IntegracionesPagosView': React.lazy(() => import('../components/admin/views/IntegracionesPagosView').then(m => ({ default: m.IntegracionesPagosView }))  ),
  'IntegracionesRRSSView': React.lazy(() => import('../components/admin/views/IntegracionesRRSSView').then(m => ({ default: m.IntegracionesRRSSView }))  ),
  'IntegracionesServiciosView': React.lazy(() => import('../components/admin/views/IntegracionesServiciosView').then(m => ({ default: m.IntegracionesServiciosView }))  ),
  'IntegracionesTiendasView': React.lazy(() => import('../components/admin/views/IntegracionesTiendasView').then(m => ({ default: m.IntegracionesTiendasView }))  ),
  'IntegracionesView': React.lazy(() => import('../components/admin/views/IntegracionesView').then(m => ({ default: m.IntegracionesView }))  ),
  'InventarioView': React.lazy(() => import('../components/admin/views/InventarioView').then(m => ({ default: m.InventarioView }))  ),
  'LogisticaView': React.lazy(() => import('../components/admin/views/LogisticaView').then(m => ({ default: m.LogisticaView }))  ),
  'MailingView': React.lazy(() => import('../components/admin/views/MailingView').then(m => ({ default: m.MailingView }))  ),
  'MapaEnviosView': React.lazy(() => import('../components/admin/views/MapaEnviosView').then(m => ({ default: m.MapaEnviosView }))  ),
  'MarketingView': React.lazy(() => import('../components/admin/views/MarketingView').then(m => ({ default: m.MarketingView }))  ),
  'MetaBusinessView': React.lazy(() => import('../components/admin/views/MetaBusinessView').then(m => ({ default: m.MetaBusinessView }))  ),
  'MetaMapView': React.lazy(() => import('../components/admin/views/MetaMapView').then(m => ({ default: m.MetaMapView }))  ),
  'MetodosEnvioView': React.lazy(() => import('../components/admin/views/MetodosEnvioView').then(m => ({ default: m.MetodosEnvioView }))  ),
  'MetodosPagoView': React.lazy(() => import('../components/admin/views/MetodosPagoView').then(m => ({ default: m.MetodosPagoView }))  ),
  'MigracionRRSSView': React.lazy(() => import('../components/admin/views/MigracionRRSSView').then(m => ({ default: m.MigracionRRSSView }))  ),
  'OCRWorkspace': React.lazy(() => import('../components/admin/views/OCRWorkspace').then(m => ({ default: m.OCRWorkspace }))  ),
  'OrganizacionesView': React.lazy(() => import('../components/admin/views/OrganizacionesView').then(m => ({ default: m.OrganizacionesView }))  ),
  'POSView': React.lazy(() => import('../components/admin/views/POSView').then(m => ({ default: m.POSView }))  ),
  'PagosView': React.lazy(() => import('../components/admin/views/PagosView').then(m => ({ default: m.PagosView }))  ),
  'PedidosView': React.lazy(() => import('../components/admin/views/PedidosView').then(m => ({ default: m.PedidosView }))  ),
  'PersonasView': React.lazy(() => import('../components/admin/views/PersonasView').then(m => ({ default: m.PersonasView }))  ),
  'ProduccionView': React.lazy(() => import('../components/admin/views/ProduccionView').then(m => ({ default: m.ProduccionView }))  ),
  'ProyectosView': React.lazy(() => import('../components/admin/views/ProyectosView').then(m => ({ default: m.ProyectosView }))  ),
  'QrGeneratorView': React.lazy(() => import('../components/admin/views/QrGeneratorView').then(m => ({ default: m.QrGeneratorView }))  ),
  'RRSSHubView': React.lazy(() => import('../components/admin/views/RRSSHubView').then(m => ({ default: m.RRSSHubView }))  ),
  'RedesSocialesView': React.lazy(() => import('../components/admin/views/RedesSocialesView').then(m => ({ default: m.RedesSocialesView }))  ),
  'RepositorioAPIsView': React.lazy(() => import('../components/admin/views/RepositorioAPIsView').then(m => ({ default: m.RepositorioAPIsView }))  ),
  'RuedaSorteosView': React.lazy(() => import('../components/admin/views/RuedaSorteosView').then(m => ({ default: m.RuedaSorteosView }))  ),
  'RutasView': React.lazy(() => import('../components/admin/views/RutasView').then(m => ({ default: m.RutasView }))  ),
  'SEOView': React.lazy(() => import('../components/admin/views/SEOView').then(m => ({ default: m.SEOView }))  ),
  'SecondHandView': React.lazy(() => import('../components/admin/views/SecondHandView').then(m => ({ default: m.SecondHandView }))  ),
  'SistemaView': React.lazy(() => import('../components/admin/views/SistemaView').then(m => ({ default: m.SistemaView }))  ),
  'SystemLogsView': React.lazy(() => import('../components/admin/views/SystemLogsView').then(m => ({ default: m.SystemLogsView }))  ),
  'TrackingPublicoView': React.lazy(() => import('../components/admin/views/TrackingPublicoView').then(m => ({ default: m.TrackingPublicoView }))  ),
  'TransportistasView': React.lazy(() => import('../components/admin/views/TransportistasView').then(m => ({ default: m.TransportistasView }))  ),
  'UnifiedWorkspaceView': React.lazy(() => import('../components/admin/views/UnifiedWorkspaceView').then(m => ({ default: m.UnifiedWorkspaceView }))  ),
  'UserDashboardView': React.lazy(() => import('../components/admin/views/UserDashboardView').then(m => ({ default: m.UserDashboardView }))  ),
  'VehiculosView': React.lazy(() => import('../components/admin/views/VehiculosView').then(m => ({ default: m.VehiculosView }))  ),
  'WebhooksView': React.lazy(() => import('../components/admin/views/WebhooksView').then(m => ({ default: m.WebhooksView }))  ),
};
